### ISSUE TITLE
Update sentry_sdk to newest version

### ISSUE THREAD

**Issue by Chabare** [OpenAlcoholics/regular_dicers_bot#36]
```
bot_1  | Traceback (most recent call last):
bot_1  |   File "main.py", line 7, in <module>
bot_1  |     import sentry_sdk
bot_1  |   File "/usr/local/lib/python3.7/site-packages/sentry_sdk/__init__.py", line 25, in <module>
bot_1  |     from sentry_sdk.hub import Hub, init
bot_1  |   File "/usr/local/lib/python3.7/site-packages/sentry_sdk/hub.py", line 10, in <module>
bot_1  |     from sentry_sdk.client import Client
bot_1  |   File "/usr/local/lib/python3.7/site-packages/sentry_sdk/client.py", line 19, in <module>
bot_1  |     from sentry_sdk.integrations import setup_integrations
bot_1  |   File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/__init__.py", line 50, in <module>
bot_1  |     "sentry_sdk.integrations.threading.ThreadingIntegration",
bot_1  |   File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/__init__.py", line 36, in _generate_default_integrations_iterator
bot_1  |     import_string
bot_1  | TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

**Comment by Chabare** [comment]
https://github.com/getsentry/sentry-python/commit/92ca9db7a4ff9610718c9c9a435746e571089b4b is the culprit. 

Since we execute python (https://github.com/OpenAlcoholics/regular_dicers_bot/blob/557be30ce0de792d2a4969676245e54f92111154/Dockerfile#L9) with the `-OO` flag (`do -O changes and also discard docstrings; add .opt-2 before .pyc extension`), all docstrings are omitted from the source files.

This leads to the following problem:
`__doc__` is `None` -> Can't append `import_string` to `None`.

Fix: Execute python with the `-O` flag only.
